using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace VibeGame1.EditorTools
{
    /// <summary>
    /// Builds the <see cref="AnimatorController"/> for a clip-carrying forge model, from the clips the
    /// FBX actually imported.
    ///
    /// <para><b>Why an editor script and not a hand-authored controller asset.</b> Hard rule 4: everything
    /// is regenerable. A controller dragged together in the Animator window is hand-authored state that
    /// nothing can rebuild — and worse, it silently keeps pointing at stale clip sub-assets after the FBX
    /// is re-split, so the enemy plays the wrong animation with no error anywhere. Generating it from
    /// <c>AssetDatabase.LoadAllAssetsAtPath(fbx)</c> means the controller cannot disagree with the model.</para>
    ///
    /// <para><b>One state per clip, and NO transitions.</b> This looks lazy and is deliberate. The
    /// controller is not the brain — <see cref="EnemyController"/> is, and its timings come from
    /// <see cref="EnemyAttackData"/>. A state machine with authored conditions would put a SECOND
    /// timing authority in the project, and the first time a transition's exit time disagreed with a
    /// wind-up the attack would stop being parryable. <see cref="PuppetVisuals"/> therefore drives
    /// playback directly with <c>Animator.CrossFadeInFixedTime</c>, which creates its transitions
    /// dynamically and needs none authored. The controller is a clip LIBRARY with a default pose.</para>
    /// </summary>
    public static class PuppetAnimatorFactory
    {
        public const string ControllerDir = "Assets/Animation";

        /// <summary>
        /// Build (or rebuild) a controller holding every <see cref="AnimationClip"/> in
        /// <paramref name="fbxPath"/>. Returns null, having logged, when the model has no clips —
        /// which almost always means <see cref="ForgeClipSplitter"/> has not been run.
        /// </summary>
        public static AnimatorController Build(string fbxPath, string controllerName, string defaultClip)
        {
            var clips = ClipsIn(fbxPath);
            if (clips.Count == 0)
            {
                Debug.LogError("[PuppetAnimator] " + fbxPath + " contains no AnimationClips. Run " +
                    "VibeGame1/4a. Split Forge Animation Clips first — an unsplit forge FBX imports as " +
                    "one take named 'Take 001' and no named clip exists to play.");
                return null;
            }

            DataFactory.EnsureFolder(ControllerDir);
            string path = ControllerDir + "/" + controllerName + ".controller";

            // Recreate rather than patch: a controller edited in place keeps orphaned states pointing at
            // clip sub-assets that no longer exist after a re-split, and those fail silently at runtime.
            AssetDatabase.DeleteAsset(path);
            var controller = AnimatorController.CreateAnimatorControllerAtPath(path);
            var sm = controller.layers[0].stateMachine;

            AnimatorState defaultState = null;
            for (int i = 0; i < clips.Count; i++)
            {
                var clip = clips[i];
                var state = sm.AddState(clip.name);
                state.motion = clip;
                state.writeDefaultValues = true;
                if (clip.name == defaultClip) defaultState = state;
            }

            if (defaultState == null)
            {
                Debug.LogWarning("[PuppetAnimator] '" + defaultClip + "' is not one of " + fbxPath +
                    "'s clips; defaulting to '" + clips[0].name + "'. Check the clip name against " +
                    "the model's .clips.json manifest.");
                defaultState = sm.states[0].state;
            }
            sm.defaultState = defaultState;

            EditorUtility.SetDirty(controller);
            AssetDatabase.SaveAssets();
            Debug.Log("[PuppetAnimator] Built " + path + " with " + clips.Count +
                      " clip states (default '" + defaultState.name + "').");
            return controller;
        }

        /// <summary>Every real clip in the FBX, excluding Unity's __preview__ scratch clip.</summary>
        public static List<AnimationClip> ClipsIn(string fbxPath)
        {
            var found = new List<AnimationClip>();
            var all = AssetDatabase.LoadAllAssetsAtPath(fbxPath);
            if (all == null) return found;
            for (int i = 0; i < all.Length; i++)
            {
                var c = all[i] as AnimationClip;
                // "__preview__Scene" is generated by the importer for the inspector preview and is the
                // WHOLE unsplit take. Adding it would give the controller a 21-second state that looks
                // like a valid clip and plays every animation back to back.
                if (c == null || c.name.StartsWith("__preview__")) continue;
                found.Add(c);
            }
            return found;
        }

        /// <summary>Length in seconds of one named clip, or <paramref name="fallback"/>.</summary>
        public static float ClipLength(string fbxPath, string clipName, float fallback)
        {
            var clips = ClipsIn(fbxPath);
            for (int i = 0; i < clips.Count; i++)
                if (clips[i].name == clipName) return clips[i].length;
            Debug.LogWarning("[PuppetAnimator] No clip '" + clipName + "' in " + fbxPath +
                             "; using fallback length " + fallback + "s.");
            return fallback;
        }
    }
}
