using System;
using UnityEngine;

namespace VibeGame1
{
    /// <summary>
    /// A level described as data rather than as C#.
    ///
    /// The original level lives as ~200 lines of literal <c>Box("Plat_B2", new Vector3(4, 0.5f, 22), …)</c>
    /// calls inside <c>LevelGreyboxBuilder</c>. That is fine for one level and impossible for ten. This
    /// asset holds the same information declaratively so a second level is an asset, not a method.
    ///
    /// Material references are deliberately <b>string keys</b>, resolved as
    /// <c>Assets/Materials/M_{key}.mat</c>. Keeping them out of the asset means a level definition stays
    /// small, diffable in git, and does not break when materials are regenerated by
    /// <c>MaterialFactory</c> (which recreates them, invalidating hard object references).
    ///
    /// Built by <c>VibeGame1/8. Build Level From Definition</c>; produced from an existing scene by
    /// <c>VibeGame1/Export Current Level To Definition</c>.
    /// </summary>
    [CreateAssetMenu(menuName = "VibeGame1/Level Definition")]
    public class LevelDefinition : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Stable machine key for this level. Ghost recordings, leaderboards and progression all " +
                 "key off this string, so RENAMING IT ORPHANS SAVED DATA. Choose once, keep forever.")]
        public string levelId = "level_01";

        [Tooltip("Shown to the player.")]
        public string displayName = "The Hollow Ascent";

        [Tooltip("Scene file this level is built into, without the path or extension. The builder saves " +
                 "the open scene; this records which one it belongs in.")]
        public string sceneName = "Level_01";

        [Tooltip("Target completion time in seconds. Used for medals/par and as the leaderboard baseline.")]
        public float parTime = 120f;

        [Tooltip("Ordering within LevelRegistry. Lower runs first.")]
        public int orderIndex = 0;

        [Header("Run scoring")]
        [Tooltip("Run souls required before defeating the boss records this level as complete. Zero preserves legacy completion.")]
        [Min(0)] public int requiredRunSouls = 0;

        [Tooltip("Distinct non-split enemy spawners required before defeating the boss records this level as complete. Zero preserves legacy completion.")]
        [Min(0)] public int requiredRegularKills = 0;

        [Tooltip("Extra souls awarded for each split grade. Enemy base souls remain owned by EnemyController.")]
        public RunGradeBonusDef gradeBonuses = new RunGradeBonusDef();

        [Tooltip("Ordered run checkpoints. A split closes only when its named spawner dies after all prior splits.")]
        public RunSplitDef[] runSplits = new RunSplitDef[0];


        [Header("Player")]
        [Tooltip("Where the run begins. The Player prefab is placed here and LevelManager.startSpawn points at it.")]
        public Vector3 playerStart = new Vector3(0f, 1.2f, -4f);

        [Tooltip("Facing at the start, in degrees around Y.")]
        public float playerStartYaw = 0f;

        [Header("Geometry")]
        public PlatformDef[] platforms = new PlatformDef[0];

        [Tooltip("Sloped slabs. The only non-axis-aligned geometry in the game: a run you can carry speed " +
                 "down. Authored as a rise over a run, not an angle.")]
        public RampDef[] ramps = new RampDef[0];

        [Header("Contents")]
        public SpawnDef[] spawns = new SpawnDef[0];
        public PickupDef[] pickups = new PickupDef[0];
        public CheckpointDef[] checkpoints = new CheckpointDef[0];
        public TorchDef[] torches = new TorchDef[0];
        public PedestalDef[] pedestals = new PedestalDef[0];

        [Header("Traversal (2026-09-04 pivot)")]
        [Tooltip("Floating orbs that launch the player up, or let a dash carry through and re-arm it.")]
        public BalloonDef[] balloons = new BalloonDef[0];
        [Tooltip("Sheets of flowing water on the ground: the fastest surface, skated rather than run.")]
        public WaterDef[] waters = new WaterDef[0];

        [Header("Arenas")]
        [Tooltip("Every gated fight in the level, in course order: the three mini-boss arenas and the " +
                 "boss arena all use the same ArenaDef. A mini-boss arena sets clearSpawnerName and an " +
                 "exit gate; the boss arena leaves both empty and wakes the BossController instead.")]
        public ArenaDef[] arenas = new ArenaDef[0];

        [Header("Projectile Sequences")]
        [Tooltip("Optional ordered volleys. Members keep their normal EnemyData and projectile; the sequence " +
                 "only decides which authored spawner may shoot next.")]
        public ProjectileSequenceDef[] projectileSequences = new ProjectileSequenceDef[0];

        [Header("World Displays")]
        [Tooltip("Optional physical local-records board. It is generated with the level and never restores the removed screen-space BEST RUNS HUD.")]
        public WorldLeaderboardDef worldLeaderboard = new WorldLeaderboardDef();

        [Header("Sky")]
        public SkyDef sky = new SkyDef();

        [Header("Bounds")]
        public KillZoneDef killZone = new KillZoneDef();

        /// <summary>Resolves the level id defensively — an empty id would silently share save data.</summary>
        public string SafeLevelId
        {
            get { return string.IsNullOrWhiteSpace(levelId) ? name : levelId; }
        }
    }

    /// <summary>
    /// A presentation-only, world-space view of the existing local leaderboard. The builder puts every
    /// descendant on the Sky layer and removes colliders, so the display cannot alter traversal or the
    /// Default-only NavMesh bake. Runtime data still comes from <see cref="Leaderboard"/>.
    /// </summary>
    [Serializable]
    public class WorldLeaderboardDef
    {
        public bool enabled = false;
        public string name = "WorldLeaderboard";
        public Vector3 position;
        public float yaw = 180f;
        public Vector2 size = new Vector2(10f, 5f);
        [Range(1, Leaderboard.DisplayCount)] public int rowCount = Leaderboard.DisplayCount;
        public string backingMaterialKey = "Stone";
        public string glowMaterialKey = "NeonCyan";
    }

    /// <summary>A box of geometry: platform, wall, pillar or rail. Everything solid is one of these.</summary>
    [Serializable]
    public class PlatformDef
    {
        [Tooltip("Scene object name. Keep it descriptive — this is what you read in the Hierarchy when " +
                 "something is in the wrong place.")]
        public string name = "Platform";

        [Tooltip("World-space CENTRE of the box, not its corner. A platform's walkable top surface is " +
                 "centre.y + size.y/2.")]
        public Vector3 center;

        [Tooltip("Full size in metres (this becomes localScale on a unit cube).")]
        public Vector3 size = new Vector3(4f, 1f, 4f);

        [Tooltip("Material key: 'Platform' resolves to Assets/Materials/M_Platform.mat.")]
        public string materialKey = "Platform";

        [Tooltip("Add four thin neon bars along the top edges. Trims are decoration only — no collider, " +
                 "no NavMesh contribution — but they are the main thing making a ledge readable.")]
        public bool trim = false;

        [Tooltip("Material key for the trim bars, when 'trim' is on.")]
        public string trimMaterialKey = "NeonPink";

        [Tooltip("Off for anything that moves (a gate). Static geometry batches and contributes GI.")]
        public bool isStatic = true;
    }

    /// <summary>
    /// A sloped slab — the one piece of geometry in this game that is not axis-aligned.
    ///
    /// <para><b>Authored as a rise over a run, never as an angle.</b> A designer thinks "2 m up over 6 m",
    /// and so does the arc report: the run is the horizontal distance a body covers and the rise is the
    /// height it gains, which is what a jump-clearance check needs. The angle is DERIVED
    /// (<see cref="AngleDegrees"/> = atan(rise / run)); the defaults 2 over 6 are <b>18.4°</b>, which is
    /// comfortably under a CharacterController's 45° slope limit, so it is walkable in both directions.
    /// A 6-over-6 ramp would be 45° — right on the limit, and that is the point where a body starts
    /// sliding instead of walking. Keep authored ramps at or under about 35°.</para>
    ///
    /// <para><b>Pure geometry (hard rule 10).</b> A ramp is a rotated box with a collider and a renderer
    /// and no behaviour whatsoever — it never touches the player or writes a velocity. Whether a slide
    /// accelerates down it is the motor's business, read off the ground normal.</para>
    /// </summary>
    [Serializable]
    public class RampDef
    {
        [Tooltip("Scene object name.")]
        public string name = "Ramp";

        [Tooltip("The centre of the ramp's LOW EDGE, on its walkable top surface — i.e. the point you step " +
                 "on to start climbing. Put it on the top surface of the platform the ramp leaves from. " +
                 "The high edge is then basePosition + (run along yaw) + (rise up).")]
        public Vector3 basePosition;

        [Tooltip("Width across the slope, metres. 4 m matches a default platform.")]
        public float width = 4f;

        [Tooltip("HORIZONTAL length of the slope, metres — the ground the ramp covers in plan, not the " +
                 "length of the sloped face.")]
        public float run = 6f;

        [Tooltip("Height gained from the low edge to the high edge, metres. Negative is legal and makes a " +
                 "descent. rise/run gives the angle: 2/6 = 18.4°, 3/6 = 26.6°, 4/6 = 33.7°.")]
        public float rise = 2f;

        [Tooltip("Slab thickness, measured DOWN from the walkable surface, so the surface stays exactly " +
                 "where basePosition and rise put it however thick the slab is.")]
        public float thickness = 0.5f;

        [Tooltip("Direction the ramp climbs, in degrees around Y. 0 climbs toward +Z. Any angle works; " +
                 "the four cardinals are 0 / 90 / 180 / 270.")]
        public float yaw = 0f;

        [Tooltip("Material key: 'Platform' resolves to Assets/Materials/M_Platform.mat.")]
        public string materialKey = "Platform";

        [Tooltip("Off for anything that moves. Static geometry batches and contributes GI.")]
        public bool isStatic = true;

        /// <summary>The slope angle in degrees, derived from rise over run. Signed: negative descends.</summary>
        public float AngleDegrees
        {
            get { return Mathf.Atan2(rise, Mathf.Max(0.0001f, run)) * Mathf.Rad2Deg; }
        }

        /// <summary>Length of the sloped FACE — hypotenuse of run and rise. This is the slab's local z scale.</summary>
        public float SlopeLength
        {
            get { return Mathf.Sqrt(run * run + rise * rise); }
        }

        /// <summary>Horizontal unit direction the ramp climbs in, from <see cref="yaw"/>.</summary>
        public Vector3 Heading
        {
            get { return Quaternion.Euler(0f, yaw, 0f) * Vector3.forward; }
        }

        /// <summary>The slab's rotation: yawed, then pitched nose-up by the slope angle.</summary>
        public Quaternion Rotation
        {
            get { return Quaternion.Euler(-AngleDegrees, yaw, 0f); }
        }

        /// <summary>The slab's local scale as a unit cube: width across, thickness down, slope length along.</summary>
        public Vector3 BoxScale
        {
            get
            {
                return new Vector3(Mathf.Max(0.01f, width), Mathf.Max(0.01f, thickness), Mathf.Max(0.01f, SlopeLength));
            }
        }

        /// <summary>The slab's world CENTRE: half a slope along from the base, then half a thickness below the surface.</summary>
        public Vector3 BoxCenter
        {
            get
            {
                Quaternion rot = Rotation;
                return basePosition + rot * Vector3.forward * (SlopeLength * 0.5f)
                                    - rot * Vector3.up * (Mathf.Max(0.01f, thickness) * 0.5f);
            }
        }

        /// <summary>Centre of the ramp's HIGH edge, on the walkable surface — where the next platform meets it.</summary>
        public Vector3 TopPosition
        {
            get { return basePosition + Heading * run + Vector3.up * rise; }
        }
    }

    /// <summary>An enemy spawn point. The spawner owns respawn, so enemies reset with the level.</summary>
    [Serializable]
    public class SpawnDef
    {
        public string name = "Spawn_Grunt";

        [Tooltip("Prefab key: 'Enemy_Grunt' resolves to Assets/Prefabs/Enemy_Grunt.prefab. " +
                 "Tuning lives on the EnemyData the prefab points at, not here.")]
        public string prefabKey = "Enemy_Grunt";

        public Vector3 position;

        [Tooltip("Facing in degrees around Y. 180 faces -Z, toward a player arriving up the course.")]
        public float yaw = 180f;

        [Tooltip("Boss spawners are excluded from ordinary aggro and wait for the arena trigger.")]
        public bool isBoss = false;
    }

    /// <summary>A single-use item lying in the world.</summary>
    [Serializable]
    public class PickupDef
    {
        public string name = "Pickup";

        [Tooltip("Item asset name in Assets/Data/Items, without the extension — 'Grapple' or 'WallSurge'. " +
                 "A key rather than a reference so DataFactory can recreate items freely.")]
        public string itemKey = "Grapple";

        [Tooltip("Float it about 1.2 m above the platform's top surface so it reads as collectable.")]
        public Vector3 position;
    }

    /// <summary>A checkpoint volume plus the point you respawn at.</summary>
    [Serializable]
    public class CheckpointDef
    {
        [Tooltip("LevelManager.Warp() finds checkpoints BY NAME, and DebugKeys/TestMenu warp to " +
                 "'Checkpoint_1'..'Checkpoint_4'; DebugKeys F5 warps to the LAST one. Renaming " +
                 "these breaks those shortcuts.")]
        public string name = "Checkpoint_1";

        public Vector3 position;

        [Tooltip("Respawn point relative to the checkpoint. Offset it back down the course so a respawn " +
                 "does not drop you inside the trigger you just touched.")]
        public Vector3 spawnOffset = new Vector3(0f, 0.2f, -2f);
    }

    /// <summary>A light source. Cheap to author, expensive to over-use — each is a real point light.</summary>
    [Serializable]
    public class TorchDef
    {
        public string name = "Torch";

        [Tooltip("The platform's TOP surface. The post and ember are built upward from here.")]
        public Vector3 basePosition;
    }

    /// <summary>The boss gate: a slab that rises to seal the arena when the player enters.</summary>
    [Serializable]
    public class ArenaDef
    {
        [Tooltip("Off for levels with no boss.")]
        public bool enabled = false;

        public string gateName = "Gate";
        public Vector3 gateSize = new Vector3(6f, 4f, 0.5f);
        public string gateMaterialKey = "Gate";

        [Tooltip("Where the gate rests while the arena is open — usually sunk below the floor.")]
        public Vector3 gateOpenPosition;

        [Tooltip("Where the gate travels to when the fight starts.")]
        public Vector3 gateClosedPosition;

        public string triggerName = "ArenaTrigger";

        [Tooltip("Put this INSIDE the arena mouth, past the gate, so the gate closes behind the player.")]
        public Vector3 triggerPosition;

        public Vector3 triggerSize = new Vector3(6f, 4f, 2f);

        [Header("Mini-boss arena (leave empty for the boss arena)")]
        [Tooltip("Name of the SpawnDef whose enemy must die before the exit gate opens. Empty means this " +
                 "is THE boss arena: entering wakes the BossController and nothing ever reopens.")]
        public string clearSpawnerName = "";

        [Tooltip("Off for the boss arena — the run ends there, so there is nothing to open onto.")]
        public bool hasExitGate = false;

        public string exitGateName = "ExitGate";
        public Vector3 exitGateSize = new Vector3(6f, 4f, 0.5f);
        public string exitGateMaterialKey = "Gate";

        [Tooltip("Where the exit gate SITS AT REST — up, sealing the way on. This is the inverse of the " +
                 "entry gate, whose rest position is sunk.")]
        public Vector3 exitGateClosedPosition;

        [Tooltip("Where the exit gate drops to when the mini-boss dies.")]
        public Vector3 exitGateOpenPosition;

        [Header("Solar realm (optional)")]
        [Tooltip("When enabled, the existing gated arena becomes a portal sun. The gate and clear-spawner " +
                 "contract stays unchanged; only the fight's physical room moves to the remote realm.")]
        public SolarRealmDef solarRealm = new SolarRealmDef();
    }

    /// <summary>One ordered timing segment in a level run.</summary>
    [Serializable]
    public class RunSplitDef
    {
        [Tooltip("Stable display and telemetry name for this split.")]
        public string name = "Split";

        [Tooltip("The EnemySpawner whose unique kill closes this split.")]
        public string endSpawnerName = "";

        [Tooltip("Inclusive grade thresholds in ascending order. At or under S is S; over C is D.")]
        [Min(0f)] public float sSeconds = 30f;
        [Min(0f)] public float aSeconds = 35f;
        [Min(0f)] public float bSeconds = 40f;
        [Min(0f)] public float cSeconds = 45f;
    }

    /// <summary>Split grades, ordered from slowest to fastest for stable serialized values.</summary>
    public enum SplitGrade { D, C, B, A, S }

    /// <summary>Data-authored bonus souls awarded for a split grade.</summary>
    [Serializable]
    public class RunGradeBonusDef
    {
        [Min(0)] public int dSouls = 0;
        [Min(0)] public int cSouls = 0;
        [Min(0)] public int bSouls = 0;
        [Min(0)] public int aSouls = 0;
        [Min(0)] public int sSouls = 0;
    }

    /// <summary>
    /// Presentation and destinations for one same-scene boss realm. The exterior anchor is authored in
    /// world space so the sun can replace the arena without moving the route. The enemy spawner remains
    /// at its historical position in <see cref="LevelDefinition.spawns"/> and is moved to
    /// <see cref="enemySpawnPosition"/> only while the scene is built; this keeps migrations idempotent.
    /// </summary>
    [Serializable]
    public class SolarRealmDef
    {
        public bool enabled = false;
        public string themeMaterialKey = "SolarCyan";

        [Tooltip("Centre of the visible exterior sun, at the existing arena's X/Z anchor.")]
        public Vector3 exteriorCenter;
        public float exteriorRadius = 12f;
        [Tooltip("Visible plasma radius. Zero or negative uses exteriorRadius. Kept separate so a sun can " +
                 "enclose the old court without moving the gameplay portal boundary.")]
        public float visualRadius = 0f;

        [Tooltip("Centre of the disconnected enclosed fight cell.")]
        public Vector3 realmCenter;
        public float realmFloorRadius = 20f;
        public float realmShellRadius = 30f;

        public Vector3 playerEntryPosition;
        public float playerEntryYaw = 0f;

        [Tooltip("Safe exterior point on the approach side, used by standalone arena resets.")]
        public Vector3 retryPosition;
        public float retryYaw = 0f;

        [Tooltip("The existing named EnemySpawner is moved here by the builder, never in the data asset.")]
        public string enemySpawnerName = "";
        public Vector3 enemySpawnPosition;
        public float enemySpawnYaw = 180f;

        [Tooltip("Optional pickup already authored in the old court; builder moves its live instance into the realm.")]
        public string arenaPickupName = "";
        public Vector3 arenaPickupPosition;

        [Tooltip("Mini-boss realms expose their inner exit after clear and return here. Final boss leaves this off.")]
        public bool hasReturn = true;
        public Vector3 realmExitPosition;
        public Vector3 returnPosition;
        public float returnYaw = 0f;
    }

    /// <summary>
    /// A bounded route corridor used to audit where one projectile enemy can create a readable contact.
    /// It is authoring evidence, not an invisible runtime trigger: ordinary sentries still fire from their
    /// normal range, sight and facing rules.
    /// </summary>
    [Serializable]
    public class ProjectileEngagementWindowDef
    {
        [Tooltip("EnemySpawner name this route window authorizes. Multiple windows may name the same " +
                 "member when it covers alternate or vertically stacked routes.")]
        public string spawnerName = "";

        [Tooltip("World-space player-chest line used to audit this encounter beat.")]
        public Vector3 routeStart;
        public Vector3 routeEnd = Vector3.forward;

        [Tooltip("Horizontal metres either side of the authored line that still belong to this route.")]
        [Min(0.1f)] public float halfWidth = 3f;

        [Tooltip("Vertical metres from the line. This separates stacked paths such as the two T2 laps.")]
        [Min(0.1f)] public float heightTolerance = 2.5f;

        [Tooltip("Earliest and latest horizontal metres from routeStart where forecast contact may land.")]
        [Min(0f)] public float arrivalStart;
        [Min(0f)] public float arrivalEnd = 10f;
    }

    /// <summary>
    /// A route-audit group for existing projectile-enemy spawners. Records with progress gates also create
    /// a runtime volley coordinator; records without progress gates leave their sentries autonomous. A
    /// sequence never changes a projectile's damage, cue, speed, range or facing rules.
    /// </summary>
    [Serializable]
    public class ProjectileSequenceDef
    {
        public string name = "ProjectileSequence";

        [Tooltip("EnemySpawner object names in firing order.")]
        public string[] spawnerNames = new string[0];

        [Tooltip("Quiet beat after one bolt resolves before the next member may launch. The bolt's own " +
                 "flight remains the main spacing between parry contacts.")]
        public float recoveryGap = 0.11f;

        [Tooltip("Once a member has entered its normal firing band, maximum time to wait for a clear, " +
                 "frontal shot before moving on. This prevents one blocked member from silencing the row.")]
        public float readinessTimeout = 1.1f;

        [Tooltip("After a launched bolt remains unresolved this long, retire only that incoming bolt and " +
                 "continue the sequence. Zero preserves the legacy wait-for-projectile-lifetime behavior.")]
        public float shotResolutionTimeout = 0f;

        [Tooltip("World-space origin for optional per-member progress gates.")]
        public Vector3 progressOrigin;

        [Tooltip("Direction player progress is measured from progressOrigin. Zero disables progress gates.")]
        public Vector3 progressDirection;

        [Tooltip("Minimum distance along progressDirection before each member may arm. Leave empty for the " +
                 "original range-driven sequence behavior.")]
        public float[] memberProgressGates = new float[0];

        [Tooltip("Optional bounded route corridors and predicted-contact ranges. Empty keeps the legacy " +
                 "audit behavior. Duplicate spawner names describe alternate routes; these do not suppress " +
                 "otherwise valid runtime shots.")]
        public ProjectileEngagementWindowDef[] engagementWindows = new ProjectileEngagementWindowDef[0];

        /// <summary>
        /// Only explicitly progress-gated rows need a runtime coordinator. Route-only records exist so the
        /// encounter report can audit ordinary autonomous sentries without turning them into one-shot events.
        /// </summary>
        public bool CoordinatesRuntime
        {
            get { return memberProgressGates != null && memberProgressGates.Length > 0; }
        }
    }

    /// <summary>
    /// A balloon: a floating orb the player launches off (or dashes through). See <see cref="Balloon"/>.
    /// Author it where a jump alone falls short: 14 m/s up against gravity -30 is a 3.3 m rise from
    /// wherever you touch it, and a dash through it re-arms the dash for the next one.
    /// </summary>
    [Serializable]
    public class BalloonDef
    {
        public string name = "Balloon";
        [Tooltip("Centre of the orb, world space.")]
        public Vector3 position;
        [Tooltip("Upward speed the player leaves with, m/s. Replaces the vertical speed (a capped jump).")]
        public float launchSpeed = 11f;
        [Tooltip("Seconds until the orb is back after a pop.")]
        public float respawnSeconds = 2.5f;
        [Tooltip("Trigger radius, metres.")]
        public float radius = 1.1f;
    }

    /// <summary>
    /// A sheet of flowing water on the ground. See <see cref="WaterVolume"/> and
    /// <see cref="TraversalMath.WaterStep"/>: no friction, a speed floor of groundSpeed x 1.35, and the
    /// flow added as a conveyor. Lay it ON a platform's top surface (centre.y = top + size.y / 2).
    /// </summary>
    [Serializable]
    public class WaterDef
    {
        public string name = "Water";
        [Tooltip("Centre of the sheet, world space. Its bottom face should sit on the floor.")]
        public Vector3 center;
        [Tooltip("Full size (x, thickness, z). Thin: 0.04 m reads as a film, not a slab.")]
        public Vector3 size = new Vector3(10f, 0.04f, 10f);
        [Tooltip("Flow direction, world space, flattened. Zero = still water.")]
        public Vector3 flowDirection = Vector3.forward;
        [Tooltip("Conveyor speed, m/s.")]
        public float flowSpeed = 6f;
    }

    /// <summary>A wand altar. Aim at it and press F; see WandPedestal.</summary>
    [Serializable]
    public class PedestalDef
    {
        public string name = "WandPedestal_Start";

        [Tooltip("The FLOOR surface it stands on. The plinth, crystal and glow are built upward from here.")]
        public Vector3 groundPosition;

        [Tooltip("Trigger radius. Make it wide enough to already cover the player start, so the loadout " +
                 "choice is on offer from the first frame.")]
        public float triggerRadius = 3f;
    }

    /// <summary>
    /// The starfield dome and its eclipse. Not geometry: it is on the Sky layer and is excluded from the
    /// NavMesh bake. Its parameters cannot be read back off the built mesh, so the exporter records only
    /// that a sky exists and leaves these values alone — edit them here, not in the scene.
    /// </summary>
    [Serializable]
    public class SkyDef
    {
        public bool enabled = true;
        public int starCount = 1200;
        public float radius = 25f;
        public int seed = 20260830;
        public bool includeEclipse = true;
        public float eclipseYawDeg = 0f;
        // THE BERSERK ECLIPSE. 22 deg up puts the bottom limb 3 deg above the horizon so the black
        // centre stays above eye level -- an enemy at combat range is read against the corona glow,
        // never against the black. 38 deg of diameter fills over half the vertical frame at FOV 70.
        // These default values are for a NEW definition; the shipped level carries its own copy in
        // Level_01_Level.asset, and the two must be kept equal or the pipeline and the legacy greybox
        // draw different skies. Starfield.DefaultEclipse* is the third copy. See ENGINEERING-LOG.md.
        public float eclipsePitchDeg = 22f;
        public float eclipseDiameterDeg = 38f;
    }

    /// <summary>The fall-out-of-the-world volume.</summary>
    [Serializable]
    public class KillZoneDef
    {
        public string name = "KillZone";

        [Tooltip("Centre of the kill volume. Keep it well below the lowest platform.")]
        public Vector3 center = new Vector3(0f, -25f, 95f);

        [Tooltip("Make this comfortably larger than the level's footprint — a player who clips out sideways " +
                 "should still land in it rather than falling forever.")]
        public Vector3 size = new Vector3(140f, 2f, 260f);
    }
}
