using System;
using UnityEngine;

namespace VibeGame1
{
    /// <summary>
    /// A level described as data rather than as C#.
    ///
    /// The original level lives as ~200 lines of literal <c>Box("Plat_B2", new Vector3(4, 0.5f, 22), …)</c>
    /// calls inside <c>LevelGreyboxBuilder</c>. That is fine for one level and impossible for ten. This
    /// asset holds the same information declaratively so a second level is an asset, not a method.
    ///
    /// Material references are deliberately <b>string keys</b>, resolved as
    /// <c>Assets/Materials/M_{key}.mat</c>. Keeping them out of the asset means a level definition stays
    /// small, diffable in git, and does not break when materials are regenerated by
    /// <c>MaterialFactory</c> (which recreates them, invalidating hard object references).
    ///
    /// Built by <c>VibeGame1/8. Build Level From Definition</c>; produced from an existing scene by
    /// <c>VibeGame1/Export Current Level To Definition</c>.
    /// </summary>
    [CreateAssetMenu(menuName = "VibeGame1/Level Definition")]
    public class LevelDefinition : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Stable machine key for this level. Ghost recordings, leaderboards and progression all " +
                 "key off this string, so RENAMING IT ORPHANS SAVED DATA. Choose once, keep forever.")]
        public string levelId = "level_01";

        [Tooltip("Shown to the player.")]
        public string displayName = "The Hollow Ascent";

        [Tooltip("Scene file this level is built into, without the path or extension. The builder saves " +
                 "the open scene; this records which one it belongs in.")]
        public string sceneName = "Level_01";

        [Tooltip("Target completion time in seconds. Used for medals/par and as the leaderboard baseline.")]
        public float parTime = 120f;

        [Tooltip("Ordering within LevelRegistry. Lower runs first.")]
        public int orderIndex = 0;

        [Header("Radio (2026-09-06)")]
        [Tooltip("Folder under Assets/Resources/Audio/Radio/ holding this level's playlist (mp3 / ogg / wav, played in " +
                 "name order). Empty = the levelId; a missing folder falls back to Audio/Radio/Default.")]
        public string radioFolder = "";

        [Header("Player")]
        [Tooltip("Where the run begins. The Player prefab is placed here and LevelManager.startSpawn points at it.")]
        public Vector3 playerStart = new Vector3(0f, 1.2f, -4f);

        [Tooltip("Facing at the start, in degrees around Y.")]
        public float playerStartYaw = 0f;

        [Header("Geometry")]
        public PlatformDef[] platforms = new PlatformDef[0];

        [Header("Contents")]
        public SpawnDef[] spawns = new SpawnDef[0];
        public PickupDef[] pickups = new PickupDef[0];
        public CheckpointDef[] checkpoints = new CheckpointDef[0];
        public TorchDef[] torches = new TorchDef[0];
        public PedestalDef[] pedestals = new PedestalDef[0];

        [Header("Traversal (2026-09-04 pivot)")]
        [Tooltip("Floating orbs that launch the player up, or let a dash carry through and re-arm it.")]
        public BalloonDef[] balloons = new BalloonDef[0];
        [Tooltip("Sheets of flowing water on the ground: the fastest surface, skated rather than run.")]
        public WaterDef[] waters = new WaterDef[0];

        [Header("Arenas")]
        [Tooltip("Every gated fight in the level, in course order: the three mini-boss arenas and the " +
                 "boss arena all use the same ArenaDef. A mini-boss arena sets clearSpawnerName and an " +
                 "exit gate; the boss arena leaves both empty and wakes the BossController instead.")]
        public ArenaDef[] arenas = new ArenaDef[0];

        [Header("Sky")]
        public SkyDef sky = new SkyDef();

        [Header("Bounds")]
        public KillZoneDef killZone = new KillZoneDef();

        /// <summary>Resolves the level id defensively — an empty id would silently share save data.</summary>
        public string SafeLevelId
        {
            get { return string.IsNullOrWhiteSpace(levelId) ? name : levelId; }
        }
    }

    /// <summary>A box of geometry: platform, wall, pillar or rail. Everything solid is one of these.</summary>
    [Serializable]
    public class PlatformDef
    {
        [Tooltip("Scene object name. Keep it descriptive — this is what you read in the Hierarchy when " +
                 "something is in the wrong place.")]
        public string name = "Platform";

        [Tooltip("World-space CENTRE of the box, not its corner. A platform's walkable top surface is " +
                 "centre.y + size.y/2.")]
        public Vector3 center;

        [Tooltip("Full size in metres (this becomes localScale on a unit cube).")]
        public Vector3 size = new Vector3(4f, 1f, 4f);

        [Tooltip("Material key: 'Platform' resolves to Assets/Materials/M_Platform.mat.")]
        public string materialKey = "Platform";

        [Tooltip("Add four thin neon bars along the top edges. Trims are decoration only — no collider, " +
                 "no NavMesh contribution — but they are the main thing making a ledge readable.")]
        public bool trim = false;

        [Tooltip("Material key for the trim bars, when 'trim' is on.")]
        public string trimMaterialKey = "NeonPink";

        [Tooltip("Off for anything that moves (a gate). Static geometry batches and contributes GI.")]
        public bool isStatic = true;
    }

    /// <summary>An enemy spawn point. The spawner owns respawn, so enemies reset with the level.</summary>
    [Serializable]
    public class SpawnDef
    {
        public string name = "Spawn_Grunt";

        [Tooltip("Prefab key: 'Enemy_Grunt' resolves to Assets/Prefabs/Enemy_Grunt.prefab. " +
                 "Tuning lives on the EnemyData the prefab points at, not here.")]
        public string prefabKey = "Enemy_Grunt";

        public Vector3 position;

        [Tooltip("Facing in degrees around Y. 180 faces -Z, toward a player arriving up the course.")]
        public float yaw = 180f;

        [Tooltip("Boss spawners are excluded from ordinary aggro and wait for the arena trigger.")]
        public bool isBoss = false;
    }

    /// <summary>A single-use item lying in the world.</summary>
    [Serializable]
    public class PickupDef
    {
        public string name = "Pickup";

        [Tooltip("Item asset name in Assets/Data/Items, without the extension — 'Grapple' or 'WallSurge'. " +
                 "A key rather than a reference so DataFactory can recreate items freely.")]
        public string itemKey = "Grapple";

        [Tooltip("Float it about 1.2 m above the platform's top surface so it reads as collectable.")]
        public Vector3 position;
    }

    /// <summary>A checkpoint volume plus the point you respawn at.</summary>
    [Serializable]
    public class CheckpointDef
    {
        [Tooltip("LevelManager.Warp() finds checkpoints BY NAME, and DebugKeys/TestMenu warp to " +
                 "'Checkpoint_1'..'Checkpoint_4'; DebugKeys F5 warps to the LAST one. Renaming " +
                 "these breaks those shortcuts.")]
        public string name = "Checkpoint_1";

        public Vector3 position;

        [Tooltip("Respawn point relative to the checkpoint. Offset it back down the course so a respawn " +
                 "does not drop you inside the trigger you just touched.")]
        public Vector3 spawnOffset = new Vector3(0f, 0.2f, -2f);
    }

    /// <summary>A light source. Cheap to author, expensive to over-use — each is a real point light.</summary>
    [Serializable]
    public class TorchDef
    {
        public string name = "Torch";

        [Tooltip("The platform's TOP surface. The post and ember are built upward from here.")]
        public Vector3 basePosition;
    }

    /// <summary>The boss gate: a slab that rises to seal the arena when the player enters.</summary>
    [Serializable]
    public class ArenaDef
    {
        [Tooltip("Off for levels with no boss.")]
        public bool enabled = false;

        public string gateName = "Gate";
        public Vector3 gateSize = new Vector3(6f, 4f, 0.5f);
        public string gateMaterialKey = "Gate";

        [Tooltip("Where the gate rests while the arena is open — usually sunk below the floor.")]
        public Vector3 gateOpenPosition;

        [Tooltip("Where the gate travels to when the fight starts.")]
        public Vector3 gateClosedPosition;

        public string triggerName = "ArenaTrigger";

        [Tooltip("Put this INSIDE the arena mouth, past the gate, so the gate closes behind the player.")]
        public Vector3 triggerPosition;

        public Vector3 triggerSize = new Vector3(6f, 4f, 2f);

        [Header("Mini-boss arena (leave empty for the boss arena)")]
        [Tooltip("Name of the SpawnDef whose enemy must die before the exit gate opens. Empty means this " +
                 "is THE boss arena: entering wakes the BossController and nothing ever reopens.")]
        public string clearSpawnerName = "";

        [Tooltip("Off for the boss arena — the run ends there, so there is nothing to open onto.")]
        public bool hasExitGate = false;

        public string exitGateName = "ExitGate";
        public Vector3 exitGateSize = new Vector3(6f, 4f, 0.5f);
        public string exitGateMaterialKey = "Gate";

        [Tooltip("Where the exit gate SITS AT REST — up, sealing the way on. This is the inverse of the " +
                 "entry gate, whose rest position is sunk.")]
        public Vector3 exitGateClosedPosition;

        [Tooltip("Where the exit gate drops to when the mini-boss dies.")]
        public Vector3 exitGateOpenPosition;
    }

    /// <summary>
    /// A balloon: a floating orb the player launches off (or dashes through). See <see cref="Balloon"/>.
    /// Author it where a jump alone falls short: 14 m/s up against gravity -30 is a 3.3 m rise from
    /// wherever you touch it, and a dash through it re-arms the dash for the next one.
    /// </summary>
    [Serializable]
    public class BalloonDef
    {
        public string name = "Balloon";
        [Tooltip("Centre of the orb, world space.")]
        public Vector3 position;
        [Tooltip("Upward speed the player leaves with, m/s. Replaces the vertical speed (a capped jump).")]
        public float launchSpeed = 11f;
        [Tooltip("Seconds until the orb is back after a pop.")]
        public float respawnSeconds = 2.5f;
        [Tooltip("Trigger radius, metres.")]
        public float radius = 1.1f;
    }

    /// <summary>
    /// A sheet of flowing water on the ground. See <see cref="WaterVolume"/> and
    /// <see cref="TraversalMath.WaterStep"/>: no friction, a speed floor of groundSpeed x 1.35, and the
    /// flow added as a conveyor. Lay it ON a platform's top surface (centre.y = top + size.y / 2).
    /// </summary>
    [Serializable]
    public class WaterDef
    {
        public string name = "Water";
        [Tooltip("Centre of the sheet, world space. Its bottom face should sit on the floor.")]
        public Vector3 center;
        [Tooltip("Full size (x, thickness, z). Thin: 0.04 m reads as a film, not a slab.")]
        public Vector3 size = new Vector3(10f, 0.04f, 10f);
        [Tooltip("Flow direction, world space, flattened. Zero = still water.")]
        public Vector3 flowDirection = Vector3.forward;
        [Tooltip("Conveyor speed, m/s.")]
        public float flowSpeed = 6f;
    }

    /// <summary>A wand altar. Aim at it and press F; see WandPedestal.</summary>
    [Serializable]
    public class PedestalDef
    {
        public string name = "WandPedestal_Start";

        [Tooltip("The FLOOR surface it stands on. The plinth, crystal and glow are built upward from here.")]
        public Vector3 groundPosition;

        [Tooltip("Trigger radius. Make it wide enough to already cover the player start, so the loadout " +
                 "choice is on offer from the first frame.")]
        public float triggerRadius = 3f;
    }

    /// <summary>
    /// The starfield dome and its eclipse. Not geometry: it is on the Sky layer and is excluded from the
    /// NavMesh bake. Its parameters cannot be read back off the built mesh, so the exporter records only
    /// that a sky exists and leaves these values alone — edit them here, not in the scene.
    /// </summary>
    [Serializable]
    public class SkyDef
    {
        public bool enabled = true;
        public int starCount = 1200;
        public float radius = 25f;
        public int seed = 20260830;
        public bool includeEclipse = true;
        public float eclipseYawDeg = 0f;
        // THE BERSERK ECLIPSE. 22 deg up puts the bottom limb 3 deg above the horizon so the black
        // centre stays above eye level -- an enemy at combat range is read against the corona glow,
        // never against the black. 38 deg of diameter fills over half the vertical frame at FOV 70.
        // These default values are for a NEW definition; the shipped level carries its own copy in
        // Level_01_Level.asset, and the two must be kept equal or the pipeline and the legacy greybox
        // draw different skies. Starfield.DefaultEclipse* is the third copy. See ENGINEERING-LOG.md.
        public float eclipsePitchDeg = 22f;
        public float eclipseDiameterDeg = 38f;
    }

    /// <summary>The fall-out-of-the-world volume.</summary>
    [Serializable]
    public class KillZoneDef
    {
        public string name = "KillZone";

        [Tooltip("Centre of the kill volume. Keep it well below the lowest platform.")]
        public Vector3 center = new Vector3(0f, -25f, 95f);

        [Tooltip("Make this comfortably larger than the level's footprint — a player who clips out sideways " +
                 "should still land in it rather than falling forever.")]
        public Vector3 size = new Vector3(140f, 2f, 260f);
    }
}
